# Generated by Django 2.2.6 on 2021-02-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('levels', models.CharField(max_length=250)),
                ('class_held', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['staff_no'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('student_class', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['student_no'],
            },
        ),
        migrations.CreateModel(
            name='Teacher_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_fullname', models.CharField(max_length=250)),
                ('class_teacher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoso_app.Staffs')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_firstname', to='contoso_app.Students')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_lastname', to='contoso_app.Students')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_class', to='contoso_app.Students')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_student', to='contoso_app.Students')),
            ],
        ),
    ]
