# Generated by Django 2.2.6 on 2021-02-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_student',
            name='class_teacher_fullname',
        ),
        migrations.RemoveField(
            model_name='teacher_student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher_student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher_student',
            name='student_class',
        ),
    ]
