# Generated by Django 2.2.6 on 2021-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_app', '0002_auto_20210206_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='class_held',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='levels',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='staff_no',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_class',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_no',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
