# Generated by Django 2.2.6 on 2021-02-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_app', '0003_auto_20210207_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_student',
            old_name='student_no',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teacher_student',
            old_name='class_teacher_no',
            new_name='teacher',
        ),
    ]
